### ISSUE TITLE
Question: How to support Monthly Leaderboards

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa-games/skills-gameon-sdk-js#43]
# Question

What would the code in `LaunchRequestHandler` look like if we wanted to support monthly leaderboards?

There are comments in the code for `enterMatch` that references `getTournamentsByTitle` and `getMatchListForPlayer`.

The following functions use `matchId`:
-  `enterMatch`
- `submitScore`
- `getPlayerScore`
- `getLeaderboard`

The following function uses `tournamentId`:
- `newPlayer`

**Comment by anfazio** [comment]
Good question - instead of calling `newPlayer` you would look up the available tournaments using `getMatchListForPlayer` and then call `enterMatch` with the tournament ID for your monthly tournament. This should be fairly simple if you're only running a single monthly tournament at a time, but you might need to add some logic to select the right one if you're running more than one tournament at a time.
